import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'KR' | 'ID' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isChangingLanguage: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  KR: {
    home: '홈',
    planner: '코어 스페이스',
    mutuals: '뮤추얼 매치',
    settings: '설정',
    language: '언어',
    login: '로그인',
    logout: '로그아웃',
    explore: '탐색',
    dashboard: '대시보드',
    welcome: '안녕하세요',
    concertKit: '콘서트 키트',
    budget: '예산',
    itinerary: '일정',
    dresscode: '드레스코드',
    checklist: '체크리스트',
    calculate: '계산하기',
    location: '위치',
    days: '일수',
    estimatedTotal: '예상 총 비용',
    heroTitle: 'ONE SPACE FOR EVERY COER.',
    heroSubtitle: '코어(Coer)를 위한 최고의 콘서트 플래너',
    startPlanning: '계획 시작하기',
    exclusiveFandom: '코어 팬덤 전용',
    heroDescription: '투어 계획을 통합하고, 새로운 뮤추얼을 찾고, 코어 팬덤을 위해 독점적으로 디자인된 하나의 미니멀한 공간에서 모든 Cortis 콘서트 니즈를 관리하세요.',
    joinWithGoogle: 'Google로 코어커넥트 가입하기',
    aiAssistantTitle: '코어 스페이스 어시스턴트',
    aiAssistantDesc: 'Cortis 세계관과 콘서트 히스토리를 모두 알고 있는 AI 기반 콘서트 플래너.',
    mutualMatchTitle: '뮤추얼 매치',
    mutualMatchDesc: '같은 도시와 콘서트 날짜로 향하는 다른 코어들과 연결하세요.',
    secureVaultTitle: '보안 금고',
    secureVaultDesc: '여행 계획과 개인 팬덤 데이터는 암호화되어 안전하게 보호됩니다.',
    planArchivedAlert: '계획이 보관함에 저장되었습니다!',
    comingSoon: '곧 출시됩니다! 같은 공연장에 가는 코어들과 연결하세요.',
    hello: '안녕,',
    concertHub: '콘서트 허브 & 소셜 피드',
    communityFeed: '코어 커뮤니티 피드',
    viewAll: '모두 보기',
    trendingDiscussions: '트렌딩 토크',
    savedPlans: '저장된 콘서트 계획',
    viewJourney: '여정 보기',
    cortisSchedule: 'Cortis 일정',
    createYourKit: '나만의 키트 만들기',
    joinDiscussion: '실시간 토론에 참여하세요',
    noPlansDesc: '코어가 코어를 위해 만든 단 몇 번의 클릭으로 나만의 콘서트 여정을 완성하세요.',
    journeyStarts: 'Cortis 월드에서의 고품격 큐레이팅 여정이 여기서 시작됩니다.',
    premiumJourney: '프리미엄 여정',
    algocuration: '을(를) 위한 알고리즘 큐레이팅',
    editInput: '정보 수정',
    archivePlan: '계획 보관하기',
    targetLocation: '목적지 설정',
    budgetLabel: '예산',
    durationLabel: '기간 (일)',
    summoningAssistant: '어시스턴트 소환 중...',
    generateMyPlan: '계획 생성하기',
    totalBudget: '총 예산',
    day: '일차',
    changingLanguage: '시스템 언어를 변경하는 중...',
    selectLanguage: '언어 선택',
    profileAndAccount: '프로필 및 계정',
    editProfile: '프로필 수정',
    displayName: '표시 이름',
    username: '사용자 이름',
    bio: '소개',
    saveChanges: '변경사항 저장',
    privacy: '개인정보 보호',
    publicProfile: '공개 프로필',
    sharePlans: 'Coer Space 계획 공유',
    systemAndLanguage: '시스템 및 언어',
    clearCache: '앱 캐시 삭제',
    accountSession: '계정 세션',
    logoutAccount: '로그아웃',
    cancel: '취소',
    confirmDeleteTitle: '이 계획을 정말 삭제하시겠습니까?',
    deleteAction: '삭제',
    reportBug: '버그/문제 신고',
    privacyPolicy: '개인정보 보호정책 및 약관',
    reportBugTitle: '버그 신고',
    reportBugDesc: '문제가 발생했나요? dffaseptember@gmail.com으로 이메일을 보내주세요.',
    privacyTitle: '개인정보 보호정책',
    privacyDesc: 'CoerConnect는 귀하의 데이터를 존중합니다. 당사는 귀하의 콘서트 계획과 개인 정보를 제3자에게 판매하지 않으며, 암호화를 통해 안전하게 보호합니다.',
    close: '닫기',
    whatIsCoerSpace: 'Coer Space란 무엇인가요?',
    coerSpaceExplanation: '코어 스페이스는 목적지에서의 교통, 숙소 예상 구성, 일일 여행 일정까지 Cortis 콘서트 전반의 여행 계획(itinerary)을 자동으로 작성할 수 있도록 특별 설계된 스마트 어시스턴트입니다.',
    dataProtected: '데이터 보호됨',
    privacyExplanation: '귀하의 예산, 위치, 여행 기간 정보는 안전하게 암호화됩니다. 본 여행 계획은 비공개로 유지되며 귀하의 허가 없이는 커뮤니티에 공유되지 않습니다.',
    originLabel: '출발 도시 및 국가',
    departureDateLabel: '출발일',
    returnDateLabel: '귀국일',
    selectConcertLabel: 'Cortis 콘서트 선택',
    budgetWarning: '예산 부족. 국가 간 여행(왕복 항공권, 숙박, 콘서트 티켓)의 최소 예상 비용은 약 인도네시아 출발 Rp12,000,000 - Rp15,000,000(1,200,000원 - 1,500,000원)입니다. 안전한 일정을 생성할 수 있도록 예산을 다시 조정해 주세요.',
    wizardIntroTitle: '2026 CORTIS 투어 <PUT YOUR PHONE DOWN>를 매우 상세하게 계획하세요',
    next: '다음',
    back: '이전',
    start: '시작하기'
  },
  ID: {
    home: 'Beranda',
    planner: 'Coer Space',
    mutuals: 'Mutual Match',
    settings: 'Pengaturan',
    language: 'Bahasa',
    login: 'Masuk',
    logout: 'Keluar',
    explore: 'Jelajah',
    dashboard: 'Dasbor',
    welcome: 'Selamat Datang',
    concertKit: 'Kit Konser',
    budget: 'Anggaran',
    itinerary: 'Rencana Perjalanan',
    dresscode: 'Dresscode',
    checklist: 'Daftar Periksa',
    calculate: 'Hitung Sekarang',
    location: 'Lokasi',
    days: 'Jumlah Hari',
    estimatedTotal: 'Total Estimasi',
    heroTitle: 'ONE SPACE FOR EVERY COER.',
    heroSubtitle: 'Asisten rencana konser terbaik untuk Coer',
    startPlanning: 'Mulai Merencana',
    exclusiveFandom: 'EKSKLUSIF UNTUK FANDOM COER',
    heroDescription: 'Satukan rencana tur, temukan mutual baru, dan kelola seluruh kebutuhan konser Cortis Anda dalam satu ruang minimalis yang dirancang eksklusif untuk fandom Coer.',
    joinWithGoogle: 'Bergabung dengan Google',
    aiAssistantTitle: 'Coer Space Assistant',
    aiAssistantDesc: 'Perencana konser berbasis AI yang tahu segalanya tentang lore Cortis dan sejarah konser.',
    mutualMatchTitle: 'Mutual Match',
    mutualMatchDesc: 'Terhubung dengan Coer lain yang pergi ke kota dan tanggal konser yang sama.',
    secureVaultTitle: 'Secure Vault',
    secureVaultDesc: 'Rencana perjalanan dan data fandom pribadi Anda dienkripsi dan dilindungi.',
    planArchivedAlert: 'Rencana berhasil disimpan di vault Anda!',
    comingSoon: 'Fitur segera hadir! Terhubung dengan sesama Coer di lokasi yang sama.',
    hello: 'HALO,',
    concertHub: 'CONCERT HUB & SOCIAL FEED',
    communityFeed: 'COER COMMUNITY FEED',
    viewAll: 'Lihat Semua',
    trendingDiscussions: 'TRENDING DISCUSSIONS',
    savedPlans: 'RENCANA KONSERT TERSIMPAN',
    viewJourney: 'Lihat Detail',
    cortisSchedule: 'JADWAL CORTIS',
    createYourKit: 'Buat Kit Konser',
    joinDiscussion: 'Ikuti diskusi secara real-time',
    noPlansDesc: 'Perjalanan konser impian Anda hanya dalam beberapa klik saja, oleh Coer, untuk Coer.',
    journeyStarts: 'Perjalanan terkurasi kelas atas Anda di dunia Cortis dimulai di sini.',
    premiumJourney: 'PREMIUM JOURNEY',
    algocuration: 'Dikurasi secara algoritmik untuk',
    editInput: 'Edit Input',
    archivePlan: 'Simpan Rencana',
    targetLocation: 'Lokasi Tujuan',
    budgetLabel: 'Anggaran',
    durationLabel: 'Durasi (Hari)',
    summoningAssistant: 'Memanggil Assistant...',
    generateMyPlan: 'BUAT RENCANAKU',
    totalBudget: 'Total Anggaran',
    day: 'Hari',
    changingLanguage: 'Sistem sedang mengubah bahasa...',
    selectLanguage: 'Pilih Bahasa',
    profileAndAccount: 'PROFIL & AKUN',
    editProfile: 'Edit Profil',
    displayName: 'Nama Tampilan',
    username: 'Username',
    bio: 'Bio',
    saveChanges: 'Simpan Perubahan',
    privacy: 'PRIVASI',
    publicProfile: 'Profil Publik',
    sharePlans: 'Bagikan Rencana Coer Space',
    systemAndLanguage: 'SISTEM & BAHASA',
    clearCache: 'Hapus Cache Aplikasi',
    accountSession: 'SESI AKUN',
    logoutAccount: 'Keluar Akun',
    cancel: 'Batal',
    confirmDeleteTitle: 'Yakin ingin menghapus rencana ini?',
    deleteAction: 'Hapus',
    reportBug: 'Laporkan Bug / Masalah',
    privacyPolicy: 'Kebijakan Privasi & Ketentuan',
    reportBugTitle: 'Laporkan Masalah',
    reportBugDesc: 'Ada kendala? Kirimkan email ke dffaseptember@gmail.com dengan detail masalah Anda.',
    privacyTitle: 'Kebijakan Privasi',
    privacyDesc: 'CoerConnect sangat menghargai privasi Anda. Kami tidak menjual data rencana konser atau informasi pribadi Anda ke pihak ketiga. Semua data disimpan dengan enkripsi aman.',
    close: 'Tutup',
    whatIsCoerSpace: 'Apa itu Coer Space?',
    coerSpaceExplanation: 'Coer Space adalah asisten cerdas yang dirancang khusus untuk membantu Anda menyusun seluruh rangkaian rencana perjalanan (itinerary) konser Cortis secara otomatis, mulai dari estimasi transportasi, akomodasi, hingga jadwal harian di kota tujuan.',
    dataProtected: 'Data Anda Dilindungi',
    privacyExplanation: 'Seluruh informasi anggaran, lokasi, dan durasi perjalanan Anda dienkripsi dengan aman. Rencana ini bersifat privat dan tidak akan dibagikan ke komunitas kecuali atas izin Anda.',
    originLabel: 'KOTA & NEGARA ASAL',
    departureDateLabel: 'TANGGAL KEBERANGKATAN',
    returnDateLabel: 'TANGGAL KEPULANGAN',
    selectConcertLabel: 'PILIH KONSER CORTIS',
    budgetWarning: 'Anggaraan Kurang Memadai. Estimasi biaya minimum perjalanan antarnegara (Tiket pesawat PP, Penginapan, & Tiket Konser) berkisar antara Rp12.000.000 - Rp15.000.000. Mohon sesuaikan kembali anggaran Anda agar sistem dapat membuat itinerary yang aman.',
    wizardIntroTitle: 'Rencanakan konser 2026 CORTIS TOUR <PUT YOUR PHONE DOWN> dengan sangat terperinci',
    next: 'Selanjutnya',
    back: 'Kembali',
    start: 'Mulai'
  },
  EN: {
    home: 'Home',
    planner: 'Coer Space',
    mutuals: 'Mutual Match',
    settings: 'Settings',
    language: 'Language',
    login: 'Login',
    logout: 'Logout',
    explore: 'Explore',
    dashboard: 'Dashboard',
    welcome: 'Welcome',
    concertKit: 'Concert Kit',
    budget: 'Budget',
    itinerary: 'Itinerary',
    dresscode: 'Dresscode',
    checklist: 'Checklist',
    calculate: 'Calculate Now',
    location: 'Location',
    days: 'Total Days',
    estimatedTotal: 'Estimated Total',
    heroTitle: 'ONE SPACE FOR EVERY COER.',
    heroSubtitle: 'The ultimate concert planning assistant for Coer',
    startPlanning: 'Start Planning',
    exclusiveFandom: 'EXCLUSIVE FOR COER FANDOM',
    heroDescription: 'Unify your tour plans, find new mutuals, and manage all your Cortis concert needs in one minimalist space designed exclusively for the Coer fandom.',
    joinWithGoogle: 'Join CoerConnect with Google',
    aiAssistantTitle: 'Coer Space Assistant',
    aiAssistantDesc: 'AI-powered concert planner that knows everything about Cortis lore and concert history.',
    mutualMatchTitle: 'Mutual Match',
    mutualMatchDesc: 'Connect with other Coers heading to the same city and concert date.',
    secureVaultTitle: 'Secure Vault',
    secureVaultDesc: 'Your travel plans and personal fandom data are encrypted and protected.',
    planArchivedAlert: 'Plan archived in your vault!',
    comingSoon: 'Feature coming soon! Connect with fellow Coers heading to the same venue.',
    hello: 'HELLO,',
    concertHub: 'CONCERT HUB & SOCIAL FEED',
    communityFeed: 'COER COMMUNITY FEED',
    viewAll: 'View All',
    trendingDiscussions: 'TRENDING DISCUSSIONS',
    savedPlans: 'SAVED CONCERT PLANS',
    viewJourney: 'View Journey',
    cortisSchedule: 'CORTIS SCHEDULE',
    createYourKit: 'Create Your Kit',
    joinDiscussion: 'Join the discussion in real-time',
    noPlansDesc: 'Your generated concert journey is just a few clicks away, by Coer, for Coer.',
    journeyStarts: 'Your high-end curated journey through the Cortis world begins here.',
    premiumJourney: 'PREMIUM JOURNEY',
    algocuration: 'Algorithmically curated for',
    editInput: 'Edit Input',
    archivePlan: 'Archive Plan',
    targetLocation: 'Target Location',
    budgetLabel: 'Budget',
    durationLabel: 'Duration (Days)',
    summoningAssistant: 'Summoning Assistant...',
    generateMyPlan: 'GENERATE MY PLAN',
    totalBudget: 'Total Budget',
    day: 'Day',
    changingLanguage: 'Applying language settings...',
    selectLanguage: 'Select Language',
    profileAndAccount: 'PROFILE & ACCOUNT',
    editProfile: 'Edit Profile',
    displayName: 'Display Name',
    username: 'Username',
    bio: 'Bio',
    saveChanges: 'Save Changes',
    privacy: 'PRIVACY',
    publicProfile: 'Public Profile',
    sharePlans: 'Share Coer Space Plans',
    systemAndLanguage: 'SYSTEM & LANGUAGE',
    clearCache: 'Clear App Cache',
    accountSession: 'ACCOUNT SESSION',
    logoutAccount: 'Log Out',
    cancel: 'Cancel',
    confirmDeleteTitle: 'Are you sure you want to delete this plan?',
    deleteAction: 'Delete',
    reportBug: 'Report Bug / Issue',
    privacyPolicy: 'Privacy Policy & Terms',
    reportBugTitle: 'Report an Issue',
    reportBugDesc: 'Found a bug? Send us an email at dffaseptember@gmail.com with the details.',
    privacyTitle: 'Privacy Policy',
    privacyDesc: 'CoerConnect values your privacy. We do not sell your concert plans or personal information to third parties. All data is kept secure with industry-standard encryption.',
    close: 'Close',
    whatIsCoerSpace: 'What is Coer Space?',
    coerSpaceExplanation: 'Coer Space is an intelligent assistant designed specifically to help you automatically organize your entire Cortis concert travel itinerary, spanning transportation estimates, accommodation, and daily schedules in your target city.',
    dataProtected: 'Your Data is Protected',
    privacyExplanation: 'All information regarding your budget, location, and trip duration is securely encrypted. This plan remains private and will not be shared with the community without your explicit permission.',
    originLabel: 'ORIGIN CITY & COUNTRY',
    departureDateLabel: 'DEPARTURE DATE',
    returnDateLabel: 'RETURN DATE',
    selectConcertLabel: 'SELECT CORTIS CONCERT',
    budgetWarning: 'Insufficient Budget. The minimum estimated budget for international travel (round-trip flight, accommodation, & concert ticket) is between Rp12,000,000 - Rp15,000,000. Please adjust your budget so the system can generate a safe itinerary.',
    wizardIntroTitle: 'Plan the 2026 CORTIS TOUR <PUT YOUR PHONE DOWN> in great detail',
    next: 'Next',
    back: 'Back',
    start: 'Start'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ID');
  const [isChangingLanguage, setIsChangingLanguage] = useState(false);

  const setLanguage = (newLang: Language) => {
    if (newLang === language) return;
    setIsChangingLanguage(true);
    setTimeout(() => {
      setLanguageState(newLang);
      setIsChangingLanguage(false);
    }, 1200);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isChangingLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
